services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile.air
    tty: true
    environment:
      - API_DEBUG=true
      - GCP_PROJECT_ID=otomo-dev-401306
      - GOOGLE_APPLICATION_CREDENTIALS=
      - LOG_ENCODING=console
      - OPENAI_MODEL=gpt-3.5-turbo
      - BASIC_AUTH_PAIRS=root:pass
      - FIREBASE_AUTH_EMULATOR_HOST=firebase:9099
      - FIRESTORE_EMULATOR_HOST=firebase:8080
      # Must override
      - OPENAI_API_KEY=''
      - GOOGLE_MAPS_API_KEY=''
    volumes:
      - ./api:/app
    working_dir: /app
    ports:
      - 50051:50051
    command: air -c .air.toml

  firebase:
    build:
      context: ./firebase
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - ./firebase:/opt/firebase
      - ./.docker/firebase/bin/:/root/.cache:cached
      - ./.docker/firebase/config/:/root/.config:cached
    ports:
      - 4000:4000 # Emulator Suite UI
      - 5001:5001 # Clound Functions
      - 8080:8080 # Cloud Firestore
      - 9099:9099 # Firebase Authentication
      # - 9000:9000 # Realtime Database
      # - 5000:5000 # Firebase Hosting
      - 8085:8085 # Cloud Pub/Sub
      # - 9199:9199 # Cloud Storage
    working_dir: /opt/firebase
    command: firebase emulators:start --import emulator_data/ --export-on-exit -P dev
