inputs:
  firebaseToken:
    description: "firebase token"
    required: true
  firebaseProjectId:
    description: "Firebase project id"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "16"

    # Setup
    - name: Store cache
      uses: actions/cache@v3
      with:
        path: functions/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    # CD
    - name: Switch project
      uses: w9jds/firebase-action@master
      working-directory: ./firebase
      with:
        args: use ${{ inputs.firebaseProjectId }}
      env:
        FIREBASE_TOKEN: ${{ inputs.firebaseToken }}
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      working-directory: ./firebase
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ inputs.firebaseToken }}
