inputs:
  firebaseToken:
    description: "firebase token"
    required: true
  firebaseProjectId:
    description: "Firebase project id"
    required: true
  slackWebhookUrl:
    description: "slack webhook url"
    required: true
  slackChannel:
    description: "slack notify channel"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "16"

    # Setup
    - name: Store cache
      uses: actions/cache@v3
      with:
        path: functions/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    # CD
    - name: Switch project
      uses: w9jds/firebase-action@master
      with:
        args: use ${{ inputs.firebaseProjectId }}
      env:
        FIREBASE_TOKEN: ${{ secrets.firebaseToken }}
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.firebaseToken }}

    # テスト成功時はこちらのステップが実行される
    - name: Slack Notification on Success
      if: success()
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_ICON: https://avatars.githubusercontent.com/u/44036562?s=200&v=4
        SLACK_USERNAME: Github Actions
        SLACK_CHANNEL: ${{ secrets.SLACK_NOTIFY_CHANNEL }}
        SLACK_TITLE: Firebase CI success
        SLACK_MESSAGE: "✅ Firebase CI success: ${{ github.event.head_commit.message }}"
        SLACK_COLOR: good

    # テスト失敗時はこちらのステップが実行される
    - name: Slack Notification on Failure
      uses: rtCamp/action-slack-notify@v2.0.2
      if: failure()
      env:
        SLACK_ICON: https://avatars.githubusercontent.com/u/44036562?s=200&v=4
        SLACK_USERNAME: Github Actions
        SLACK_CHANNEL: ${{ secrets.SLACK_NOTIFY_CHANNEL }}
        SLACK_TITLE: Firebase CI failure
        SLACK_MESSAGE: "❌ Firebase CI failure: ${{ github.event.head_commit.message }}"
        SLACK_COLOR: danger
