name: API CI/CD

on:
  push:
    branches:
      - main
      - develop
      - release**
    paths:
      - "api/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  develop:
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop'
    environment: develop
    steps:
      - uses: actions/checkout@v3
      - name: Develop API CI/CD
        uses: ./.github/actions/api-cicd/
        with:
          branch: develop
          gcpProjectId: ${{ secrets.GCP_PROJECT_ID }}
          gcpServiceAccountEmail: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          gcpServiceAccountKey: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          slackChannel: ${{ secrets.SLACK_CHANNEL }}
