name: Firebase CI/CD

on:
  push:
    # branches:
    #   - main
    #   - develop
    #   - release**
    # paths:
    #   - 'firebase/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  develop:
    runs-on: ubuntu-latest
    # if: github.ref_name == 'develop'
    environment: develop
    steps:
      - uses: actions/checkout@v3
      - name: Develop Firebase CI/CD
        uses: ./.github/actions/firebase-cicd/
        with:
          firebaseToken: ${{ secrets.FIREBASE_TOKEN }}
          firebaseProjectId: ${{ secrets.GCP_PROJECT_ID }}
      - name: Notify to slack
        uses: ./.github/actions/notify-to-slack/
        if: ${{ always() }}
        with:
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
          slackChannel: ${{ secrets.SLACK_CHANNEL }}
